---
title: "Notes: Investiture Rules - 6 Subcategories"
author: "Florian Wisniewski"
date: "`r Sys.Date()`"
output:
  github_document:
    toc: TRUE
    number_sections: TRUE
---

```{r setup + libraries + df, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# What will we do?

+ Create variables for the following 6 subcategories of an investiture vote, based on the data in erdda and literature (Rasch, Martin, Cheibub: *Unpacking Investiture Rules*)

+ Check relationship between those subcategories for all types of governments in erdda: is there a relationship between investiture procedures and cabinet bargaining duration?

# Special remarks in some cases?

## BELGIUM

+ change in constitution 1993

## GREAT BRITAIN

+ Queen's Speech as mechanism is not particularly a parliamentary investiture vote - but Kelso considers it to be at least some form of investiture in the British case study

## GERMANY

+ ballots in chancellor's investiture are cast in secrecy - it is a "Gewissensentscheidung"

## IRELAND

+ in case the Taoiseach is not approved, there is no real rule as to what has to be done

## SPAIN

+ change of decision rule after first IV round fails

## POLAND

+ high degree of cooperation between the Sejm and the Polish President in IV procedure
  + *Round 1*: President appoints cabinet; Sejm votes - if IV passed, President appoints within 14 days (abs. majority), if not = Round 2
  + *Round 2* (if R1 failed): Sejm selects new cabinet and votes - if IV then passed, President appoints immediately (abs. majority), if not = Round 3
  + *Round 3* (if R2 also failed): R2 fails, if Sejm failed to select new cabinet within 14 days; then, the President has the right to appoint another cabinet; if this fails the vote in the Sejm, too, new elections are called by the President
  
## PORTUGAL

+ negative investiture rules - it is up to the parliament to provide a negative majority to disapprove of a cabinet
  + as the president appoints a "designated" cabinet, but this cabinet (because of the negative majority rules) does not have to gain support of parliament, Leston-Bandeira et al. state that Portugal can also be considered as an *ex post* IV

## SWEDEN

+ negative IV rules: PM is invested if less than half of the MPs vote **against** him/her

+ constitutional reform in 1975: before = appointment of PM directly through the monarch, no IV procedure; after 1975, IV procedure, designated PM appointed by Speaker of the Riksdag

## NETHERLANDS

+ it is not necessarily so, that a government dissolution has to lead to new general elections

# Category I: Timing

## BELGIUM

+ *ex post*: conducted **AFTER** monarch formally appointed coalition; gov. is already in charge

## GREAT BRITAIN

+ *ex post*: conducted **AFTER** monarch formally appointed prime minister to form a government; gov. is already in charge

## GERMANY

+ *ex ante*: vote takes place after general election; President chooses Kanzler/in, this is voted upon in the Bundestag; first after a passed vote, the Kanzler/in is appointed officially

## HUNGARY

+ *ex ante*: the PM has to be affirmed first in the IV, before this he has no power

## IRELAND

+ *ex ante*: Taoiseach has to be elected first, has no real power before this; second IV is cast on his cabinet; after this, both are in power

## ITALY

+ *ex post*: IV is cast after appointment of gov. by President, which is formally in power by then

## SPAIN

+ *ex ante*: investiture procedure takes place after general elections, PM is chosen by the King but then voted for or against in the procedure. As this PM is not formally in charge until he passed the vote, it is coded as 1

## POLAND

+ *ex ante*: President appoints the PM-designate (and his suggestion of cabinet) - Sejm votes in favour of her/him (or not); if he/she passes the vote, he is appointed regularly

## CZECH REPUBLIC

+ *ex post*: government and PM have their full powers after appointment through the president - but they have to seek the IV in a set timeframe (30 days after appointment)

## ROMANIA

+ *ex ante*: PM is appointed, but is only PM-designate, until confirmed by IV

## PORTUGAL

+ *ex post*: PM and cabinet are "designated" to come to power - but because of the decision rule = neg. majority and the future gov. does not need explicit support of the parliament, it is technically already in power

## SWEDEN

+ *ex ante*: Speaker suggests a new PM on the basis of situation in parliament - PM is investet as soon as he is approved by the MPs through the IV

## NETHERLANDS

+ 

# Category II: Right to nominate

## BELGIUM

+ Constitution says: "*King* appoints and dismisses cabinet ministers"

## GREAT BRITAIN

+ The Queen appoints the prime minister; but: since 1974, all parties have a designated leader, so the role of this appointment is not that important

## GERMANY

+ special here: de jure = President picks a candidate, Bundestag elects the candidate
  + but de facto: the President always picked (and always will) the majority solution and convenes with the members of the Bundestag on whom he should choose (therefore, I coded this as 0 "by parliament")
  
## HUNGARY

+ President has right to nominate the PM-to-be

## IRELAND

+ Nomination of the Taoiseach is up to the Second Chamber, the Dáil

## ITALY

+ President appoints government

## SPAIN

+ King nominates the PM who is to be invested or not

## POLAND

+ Nomination through Head of State, which is the President

## CZECH REPUBLIC

+ PM as well as government ministers are appointed by the President

## ROMANIA

+ President of Romania appoints

## PORTUGAL

+ President of Portugal appoints

## SWEDEN

+ Appointment through Speaker of the Riksdag (coded as 0, "appointment by parliament")

## NETHERLANDS

+ 


# Category III: Who votes

## BELGIUM

+ 1919 until 1995: both chambers
+ from 1995 onwards: only one

## GREAT BRITAIN

+ Queen's speech is delivered to both the House of Commons and the House of Lords
  + Lords: only followed by a debate; no vote
  + Commons: followed by a longer debate; designated opposition can make amendments - "stress test" for the coming government - at the end, there is a vote
  
## GERMANY

+ The Bundestag, so one chamber

## HUNGARY

+ President appoints - Parliament elects; HUN only one chamber

## IRELAND

+ Vote is cast by the Dáil

## ITALY

+ Government has to acquire positive vote in both chambers

## SPAIN

+ Chamber of Deputies, Senate has no say in the IV-procedure

## POLAND 

+ Sejm votes

## CZECH REPUBLIC

+ Chamber of Deputies votes, Senate exists as second chamber, but has no say concerning the IV

## ROMANIA

+ Both chambers vote in a connected hearing of the gov. programme

## PORTUGAL

+ Assembleia da Republicá votes (unicameral system)

## SWEDEN

+ Sweden is unicameral since the reform of 1971; before that, only the Second Chamber had a crucial role in government formation process (so coded as 1, also before 1971)

## NETHERLANDS

+ 


# Category IV: Target of the vote

## BELGIUM

+ whole cabinet

## GREAT BRITAIN

+ combination: Queen's speech is a vague outline of gov. programme; but: if failure of vote, the PM is likely to be expected to resign, so it is somehow also a vote on his position

## GERMANY

+ target is the chancellor-to-be, so head of government, coded as 1

## HUNGARY

+ Head of state, PM, so coded as 1

## IRELAND

+ Target of first IV is the Taoiseach; subsequently, he presents to the Dáil his cabinet ministers, which are voted for/against in a second IV

## ITALY

+ whole government is voted upon as a package

## SPAIN

+ Target is the PM-to-be = coded as 1

## POLAND

+ Target is whole cabinet (the PM and his ministers) = coded as 2
  + one could also argue that it should be coded as 4, as the PM presents an exposé to the Sejm, as an outline of his gov. programme, but as the vote itself is (acc. to Zubek) cast on the cabinet-to-be, I coded this as 2

## CZECH REPUBLIC

+ Target is the whole cabinet, consisting of the already appointed PM and his ministers = coded as 2

## ROMANIA

+ Target is, as mentioned in Chiva's chapter about Romania, the government programme, so it is about a policy approach by the designated PM and his/her cabinet

## PORTUGAL

+ Target is the government as a whole, but through a discussion of the government program, so it can be considered as 4

## SWEDEN

+ Easy case, the target is the designated PM; so, I coded this as 1

## NETHERLANDS

+ 

# Category V: Investiture failure

## BELGIUM

+ somehow, nothing really happens; government stays in power - except for no conf vote **with** an alternative PM suggested
  + therefore, I code it NA, because it is highly dependent on what the chamber is doing after the failure, and only if this is done correctly, there are new elections to be held)
  
## GREAT BRITAIN

+ in case of failure, PM would most likely be expected to resign
  + new elections OR a newly appointed PM could be the next step - so this is again coded as NA
  
## GERMANY

+ if failed in first round (presidents pick, abs. maj.), second round is Bundestag pick, abs. maj.
+ if failed again, third/final round is plurality; minority chancellor-elect is to be picked by discretion by President (has never happened)

## HUNGARY

+ new IV is cast

## IRELAND

+ there is no real procedure for when the IV fails - could be new general elections, could also be that there is another round of casting IVs (as this is stated as "unclear" in the literature, I decided to code this as NA)

## ITALY

+ no clear procedure: looking at Draghi cabinet being sworn in in Feb. '21 - possibilities for new elections, but also for negotiations with current government (therefor coded as NA)

## SPAIN

+ new rounds of IV; with relaxation of decision rule in second round

## POLAND

+ new rounds of IV (see special country rules above, there are up to three rounds before new elections are to be cast)

## CZECH REPUBLIC

+ in case of failure, procedure will start anew = coded as 0

## ROMANIA

+ new round of IV, but if this fails again, President can call new elections (if there is no new government to be formed within 60 days)

## PORTUGAL

+ Negative IV-rules: if government is rejected, the informateur (President) chooses another formateur to form a new government

## SWEDEN

+ Speaker has four attempts to designate a new PM - if all four rounds fail, new elections are to be held = coded as 0

## NETHERLANDS

+ 

# Category VI: Decision rule

## BELGIUM

+ Coded as negative majority
  + until 1995: ex post consultation which is not obligatory
  + from 1995: explicitly stated = negative majority needed

## GREAT BRITAIN

+ Coded as simple majority, because thats the AYE-NAY-vote in the Commons

## GERMANY

+ easy case, coded as absolute majority, as third stage of failure has never happened and most likely never will

## HUNGARY

+ absolute majority (100 of the 199 MPs, if everyone attends)

## IRELAND

+ for Taoiseach: more yes, than no votes (so, as it is some kind of majority, I coded this as 1)

+ apparently the same for second IV

## ITALY

+ both chambers: simple majority - hence coded as 1

## SPAIN

+ first round of IV is abs. majority, second round is simple majority, hence coded as 1

## POLAND

+ first and second round of IV is absolute majority, lowered to simple majority in a possible third round, which has up to now never occured (hence coded as 1)

## CZECH REPUBLIC

+ simple majority, so coded as 1

## ROMANIA

+ absolute majority
  + there is a quorum requirement: has to be 50% + 1 MP for the IV
  
## PORTUGAL

+ negative decision rule = coded as 0 (more on this in first paragraph)

## SWEDEN

+ negative decision rule = coded as 0 (more on this in first paragraph)

## NETHERLANDS

+ 


####################################

# AMENDMENTS: COUNTRIES OUTSIDE RASCH-MARTIN-CHEIBUB 2015

**Finland**
For the *Finnish* case, see Paloheimo (2003) and the Finnish constitution. Information is coded from 1991 onwards, as there were a few amendmends made concerning investiture and the role of the PM.

**Denmark**
See [the Danish constitution, "Kapitel III"](https://www.regeringen.dk/grundloven/). As there is no formal investiture vote in Denmark to the knowing of the author, information here refer to the motion of no confidence.

**Austria**
See [the Austrian constitution, "Drittes Hauptstück, 2: Bundesregierung"](http://www.verfassungen.at/indexheute.htm). Austria is left out as it has no formal investiture procedure. The Bundespräsident designates a PM and he forms his government. Mostly majority governments.

**Greece**
Greek Constitution, Article 84. Absolute majority requirement.

**Iceland**
[Icelandic Constitution](https://www.government.is/library/01-Ministries/Prime-Ministrers-Office/constitution_of_iceland.pdf)
[Cheibub, Rasch, Martin 2013: Istanbul Conference Paper](https://ecpr.eu/Filestore/paperproposal/ba2bdffd-a910-4bae-9c05-bb832db684a5.pdf): Iceland as deviant case - negative decision rule

**Luxembourg**
No real information about this in the constitution, as far as the author is informed.

**Norway**
See [Aardal and Bergh (2018)](https://www.tandfonline.com/doi/pdf/10.1080/01402382.2017.1415778?needAccess=true). Norway has no formal investiture vote, therefore it is fully excluded.

**Bulgaria**
See [Bulgarian Constitution, Art. 99](https://www.wipo.int/edocs/lexdocs/laws/en/bg/bg033en.pdf). Unlike Cheibub et al. 2013 in their Conference Paper, I coded the timing to be *ex ante* in Bulgaria, as the Bulgarian Constitution clearly speaks of a "*designated* PM". Maybe, there is a deviance, because Cheibub et al. were referring to 1997, whereas here, the Constitution is to be treated "as of 2007".

**Estonia**
See [Constitution of Estonia, §89](https://www.president.ee/en/republic-of-estonia/the-constitution/). Also, see [Cheibub et al. (2013), p. 14](https://ecpr.eu/Filestore/paperproposal/ba2bdffd-a910-4bae-9c05-bb832db684a5.pdf).

**Latvia**
See [Constitution of Latvia](https://likumi.lv/ta/en/id/57980-the-constitution-of-the-republic-of-latvia). 

**Lithuania**
See [Constitution of Lithuania]()
Also, see [ParlGov Database Documentation, Döring and Manow (2021)](http://www.parlgov.org/documentation/country/).

**Malta**


**Romania**


**Slovakia**


**Slovenia**








